version: 0.2

phases:
  install:
    commands:
      - echo "Installing Nginx"
      - sudo yum update -y
      - sudo yum install nginx -y
  
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the project"
  
  post_build:
    commands:
      - echo "Configuring Nginx"
      - sudo cp index.html /usr/share/nginx/html/


# No artifacts section since you're not using any.
