version: 0.2
phases:
  install:
    commands:
      - echo Nginx installing 
      - apt-get update -y
      - apt-get install nginx -y
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring Nginx
artifacts:
  files:
    - /var/www/html/index.html