version: 0.2
phases:
  install:
    commands:
      - echo "Installing Nginx"
      - sudo yum update -y
      - sudo yum install nginx -y
  build:
    commands:
      - echo "Build started on `date`"
      - mkdir -p artifact
      - cp -r cop/* artifact/
  post_build:
    commands:
      - echo "Configuring Nginx"

artifacts:
  files:
    - artifact/**
