version: 0.2

phases:
  install:
    commands:
      - echo "Installing Nginx"
      - sudo yum update -y
      - sudo yum install nginx -y
  
  build:
    commands:
      - echo "Build started on `date`"
  
  post_build:
    commands:
      - echo "Packaging files and preparing to upload to S3"

artifacts:
  files:
    - '**/*'
  discard-paths: yes  # Optional: Flatten the directory structure

# Optional: Define a base directory if needed
# base-directory: 'build_output'
